import GlobalState from '@/context'
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppRouterCacheProvider>
          <GlobalState>
            <Navbar/>
            <main className='flex min-h-screen flex-col mt-[80px]'>{children}</main>
          </GlobalState>
        </AppRouterCacheProvider>
      </body>
    </html>
  )
}
